spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@192.168.1.18:27017/award}
  redis:
    host: ${REDIS_HOST:192.168.1.18}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    database: 0
    timeout: 5000
minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.1.18:9000}
  accessKey: ${MINIO_ACCESS_KEY:root}
  secretKey: ${MINIO_SECRET_KEY:12345678}
  bucket: ${MINIO_BUCKET:award}
service:
  secret: ${CUSTOM_SECRET:hubu!@#$%^&^}